# Generated by Django 4.2.5 on 2023-10-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='student',
            name='registrationDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
