# Generated by Django 4.2.5 on 2023-11-12 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_document_alter_student_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='document',
            new_name='age',
        ),
    ]
